// Code generated by protoc-gen-go. DO NOT EDIT.
// source: learnMicroService.proto

package lms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenMsg struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMsg) Reset()         { *m = TokenMsg{} }
func (m *TokenMsg) String() string { return proto.CompactTextString(m) }
func (*TokenMsg) ProtoMessage()    {}
func (*TokenMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_43520427f71b4305, []int{0}
}

func (m *TokenMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMsg.Unmarshal(m, b)
}
func (m *TokenMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMsg.Marshal(b, m, deterministic)
}
func (m *TokenMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMsg.Merge(m, src)
}
func (m *TokenMsg) XXX_Size() int {
	return xxx_messageInfo_TokenMsg.Size(m)
}
func (m *TokenMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMsg proto.InternalMessageInfo

func (m *TokenMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenMsg) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type UserMsg struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Access               bool     `protobuf:"varint,2,opt,name=access,proto3" json:"access,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsg) Reset()         { *m = UserMsg{} }
func (m *UserMsg) String() string { return proto.CompactTextString(m) }
func (*UserMsg) ProtoMessage()    {}
func (*UserMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_43520427f71b4305, []int{1}
}

func (m *UserMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsg.Unmarshal(m, b)
}
func (m *UserMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsg.Marshal(b, m, deterministic)
}
func (m *UserMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsg.Merge(m, src)
}
func (m *UserMsg) XXX_Size() int {
	return xxx_messageInfo_UserMsg.Size(m)
}
func (m *UserMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsg proto.InternalMessageInfo

func (m *UserMsg) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserMsg) GetAccess() bool {
	if m != nil {
		return m.Access
	}
	return false
}

func (m *UserMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMsg) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type UserMsgRequest struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsgRequest) Reset()         { *m = UserMsgRequest{} }
func (m *UserMsgRequest) String() string { return proto.CompactTextString(m) }
func (*UserMsgRequest) ProtoMessage()    {}
func (*UserMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43520427f71b4305, []int{2}
}

func (m *UserMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsgRequest.Unmarshal(m, b)
}
func (m *UserMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsgRequest.Marshal(b, m, deterministic)
}
func (m *UserMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsgRequest.Merge(m, src)
}
func (m *UserMsgRequest) XXX_Size() int {
	return xxx_messageInfo_UserMsgRequest.Size(m)
}
func (m *UserMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsgRequest proto.InternalMessageInfo

func (m *UserMsgRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserMsgResponse struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMsgResponse) Reset()         { *m = UserMsgResponse{} }
func (m *UserMsgResponse) String() string { return proto.CompactTextString(m) }
func (*UserMsgResponse) ProtoMessage()    {}
func (*UserMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43520427f71b4305, []int{3}
}

func (m *UserMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMsgResponse.Unmarshal(m, b)
}
func (m *UserMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMsgResponse.Marshal(b, m, deterministic)
}
func (m *UserMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMsgResponse.Merge(m, src)
}
func (m *UserMsgResponse) XXX_Size() int {
	return xxx_messageInfo_UserMsgResponse.Size(m)
}
func (m *UserMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserMsgResponse proto.InternalMessageInfo

func (m *UserMsgResponse) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserMsgResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenMsg)(nil), "lms.TokenMsg")
	proto.RegisterType((*UserMsg)(nil), "lms.UserMsg")
	proto.RegisterType((*UserMsgRequest)(nil), "lms.UserMsgRequest")
	proto.RegisterType((*UserMsgResponse)(nil), "lms.UserMsgResponse")
}

func init() { proto.RegisterFile("learnMicroService.proto", fileDescriptor_43520427f71b4305) }

var fileDescriptor_43520427f71b4305 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xdb, 0x26, 0x6d, 0xca, 0x89, 0x3f, 0xd5, 0x51, 0x41, 0xd4, 0x09, 0x79, 0xea, 0x94,
	0xa1, 0x48, 0x30, 0xf3, 0x01, 0xba, 0x04, 0x18, 0x19, 0x4c, 0x7a, 0x4a, 0x2d, 0x92, 0x38, 0xf8,
	0x9c, 0x7e, 0x7e, 0xe4, 0x4b, 0xca, 0x1f, 0xd1, 0xed, 0xbd, 0xb3, 0xef, 0xfd, 0x9e, 0x0e, 0x6e,
	0x2b, 0xd2, 0xae, 0xd9, 0x9a, 0xc2, 0xd9, 0x67, 0x72, 0x07, 0x53, 0x50, 0xd6, 0x3a, 0xeb, 0x2d,
	0x46, 0x55, 0xcd, 0x6a, 0x03, 0xf3, 0x17, 0xfb, 0x41, 0xcd, 0x96, 0x4b, 0x5c, 0xc2, 0xd4, 0x07,
	0x9d, 0x8e, 0xef, 0xc6, 0xeb, 0xb3, 0xbc, 0x37, 0xb8, 0x80, 0x48, 0xb7, 0x26, 0x9d, 0xc8, 0x2c,
	0x48, 0xf5, 0x06, 0xc9, 0x2b, 0x93, 0x0b, 0x2b, 0x0b, 0x88, 0x3a, 0xb3, 0x93, 0x85, 0x69, 0x1e,
	0x24, 0xde, 0xc0, 0x4c, 0x17, 0x05, 0x31, 0xcb, 0xc6, 0x3c, 0x1f, 0x1c, 0x22, 0xc4, 0x8d, 0xae,
	0x29, 0x8d, 0x24, 0x47, 0x74, 0x00, 0x96, 0xce, 0x76, 0x6d, 0x1a, 0xf7, 0x40, 0x31, 0x4a, 0xc1,
	0xe5, 0x10, 0x9f, 0xd3, 0x67, 0x47, 0xec, 0xff, 0x53, 0xd4, 0x23, 0x5c, 0x7d, 0xff, 0xe1, 0xd6,
	0x36, 0x4c, 0x27, 0xaa, 0x1c, 0x91, 0x93, 0x1f, 0xe4, 0x66, 0x0f, 0xf1, 0x53, 0xe7, 0xf7, 0xb8,
	0x86, 0xc4, 0xf0, 0x41, 0x57, 0x66, 0x87, 0x17, 0x59, 0x55, 0x73, 0x76, 0xbc, 0xc2, 0xea, 0x5c,
	0xec, 0x90, 0xae, 0x46, 0xf8, 0x00, 0x49, 0x49, 0x3e, 0x78, 0xbc, 0xfe, 0xfd, 0x34, 0x94, 0x5b,
	0x2d, 0xff, 0x0e, 0xfb, 0x36, 0x6a, 0xf4, 0x3e, 0x93, 0x2b, 0xdf, 0x7f, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0xb1, 0x32, 0x38, 0x80, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Isvalid(ctx context.Context, in *TokenMsg, opts ...grpc.CallOption) (*UserMsg, error)
	GetUser(ctx context.Context, in *UserMsgRequest, opts ...grpc.CallOption) (*UserMsgResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Isvalid(ctx context.Context, in *TokenMsg, opts ...grpc.CallOption) (*UserMsg, error) {
	out := new(UserMsg)
	err := c.cc.Invoke(ctx, "/lms.Auth/isvalid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetUser(ctx context.Context, in *UserMsgRequest, opts ...grpc.CallOption) (*UserMsgResponse, error) {
	out := new(UserMsgResponse)
	err := c.cc.Invoke(ctx, "/lms.Auth/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Isvalid(context.Context, *TokenMsg) (*UserMsg, error)
	GetUser(context.Context, *UserMsgRequest) (*UserMsgResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Isvalid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Isvalid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.Auth/Isvalid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Isvalid(ctx, req.(*TokenMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lms.Auth/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetUser(ctx, req.(*UserMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lms.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "isvalid",
			Handler:    _Auth_Isvalid_Handler,
		},
		{
			MethodName: "getUser",
			Handler:    _Auth_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learnMicroService.proto",
}
